### ISSUE TITLE
Request::Context生命周期问题

### ISSUE THREAD

**Issue by jm-observer** [losfair/smr#1]
你好，请问Request::Context为什么要是static，是有什么特别的意义吗？可以改成如下代码吧，如果可以的话，我可以提一个pr。
```
#[async_trait(?Send)]
pub trait Request<'a>: BaseRequest + Deserialize<'a> + static {
  async fn init(_init_data: Self::InitData) -> &'a Self::Context;
  async fn handle(self, ctx: &'a Self::Context) -> Result<Self::Res>;
  async fn handle_with_cancellation(
    self,
    ctx: &'a Self::Context,
    _: watch::Receiver<()>,
  ) -> Result<Self::Res> {
    self.handle(ctx).await
  }
}
```

**Comment by losfair** [comment]
Hi,

这里的 `handle` 方法是在 smr fork 出的子进程中执行，ctx 在子进程初始化时由 `init` 方法创建，其生命周期是子进程的整个生命周期，所以用 `'static` 标记。

**Comment by jm-observer** [comment]
嗯，看了下代码确实是这样的。只是觉得把init方法当成Request的关联函数有点不合适，这样写会不会更好理解：
```
pub trait InitData: Serialize + for<'de> Deserialize<'de> + Send + 'static {
  async fn init(self) -> Self::Context;
```
还有1点，因为返回&'static Self::Context，就要求必须是static变量或者字符串常量，这个限制太大了。

**Comment by losfair** [comment]
> 只是觉得把init方法当成Request的关联函数有点不合适，这样写会不会更好理解

👍 这样确实感觉更好理解，PR welcome

> 因为返回&'static Self::Context，就要求必须是static变量或者字符串常量

`Box::leak` 即可 (例如 https://github.com/losfair/blueboat/blob/2b60f923f49104a7d3ae087aa31c9c46ba867b05/src/ctx.rs#L143).

这样设计是因为 `init` 可能需要取 context 中部分字段的 `'static` 引用，返回 `Self::Context` 会丢失这部分语义。
