### ISSUE TITLE
Request::Context更新问题

### ISSUE THREAD

**Issue by jm-observer** [losfair/smr#2]
你好！假设Request::Context是配置文件内容，当配置文件更新时，如何更新Worker的Context？好像也没办法手动停止Worker?

**Comment by losfair** [comment]
https://github.com/losfair/smr/pull/3 添加了手动停止 worker 的接口。

更新 context 的方法是重启 worker，比如 Blueboat 就是把同应用的不同版本视为两个不同 worker 处理的: https://github.com/losfair/blueboat/blob/74e71acb78c25dd7cd9a090cf3d409ac909e81e4/src/server.rs#L760

**Comment by jm-observer** [comment]
> #3 添加了手动停止 worker 的接口。
> 
> 更新 context 的方法是重启 worker，比如 Blueboat 就是把同应用的不同版本视为两个不同 worker 处理的: https://github.com/losfair/blueboat/blob/74e71acb78c25dd7cd9a090cf3d409ac909e81e4/src/server.rs#L760

你好，发布到crate吧

**Comment by jm-observer** [comment]
你好，啥时候将手动停止api的版本发布到crate呢？

**Comment by losfair** [comment]
你好，

0.1.1 版本发布到 crates.io 了。
